OnlineExamination/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Newtonsoft.Json;
using OnlineExamination.Controllers;
using OnlineExamination.Models;
using OnlineExamination.Models.DTO;
using OnlineExamination.Services;
using System.Drawing;
using static OnlineExamination.Models.EnumData;

namespace OnlineExaminationWeb.Controllers
{
    [Authorize(Policy = "AdminOnly")]
    public class AdminController : Controller
    {

        private readonly ILogger<AccountController> _logger;
        private readonly IAdminService _adminService;

        public AdminController(ILogger<AccountController> logger, IAdminService adminService)
        {
            _logger = logger;
            _adminService = adminService;
        }

        public async Task<ActionResult> Index()
        {
            var userInfo = JsonConvert.DeserializeObject<Roles>(HttpContext.Session.GetString("SessionUser"));
            ViewBag.UserName = userInfo.UserName;
            return View();
        }

        public async Task<ActionResult> QuesAnsCreate()
        {
            var userInfo = JsonConvert.DeserializeObject<Roles>(HttpContext.Session.GetString("SessionUser"));
            ViewBag.UserName = userInfo.UserName;
            var enumData = from CandidateLevel e in Enum.GetValues(typeof(CandidateLevel))
                           select new
                           {
                               ID = (int)e,
                               Name = e.ToString()
                           };
            ViewBag.EnumList = new SelectList(enumData, "ID", "Name");
            ViewBag.Tech = new SelectList(await _adminService.BindTechDropDownList(), "Id", "TechName");
            if (TempData["DataSaved"] != null)
            {
                ViewBag.DataSaved = TempData["DataSaved"].ToString();
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> QuesAnsCreate(QuesAnsCreateDto quesAnsCreateDto)
        {
            var userInfo = JsonConvert.DeserializeObject<Roles>(HttpContext.Session.GetString("SessionUser"));
            ViewBag.UserName = userInfo.UserName;
            if (!ModelState.IsValid)
            {
                var enumData = from CandidateLevel e in Enum.GetValues(typeof(CandidateLevel))
                               select new
                               {
                                   ID = (int)e,
                                   Name = e.ToString()
                               };
                ViewBag.EnumList = new SelectList(enumData, "ID", "Name");
                ViewBag.Tech = new SelectList(await _adminService.BindTechDropDownList(), "Id", "TechName");
                return View();
            }
            int isDataPushed = await _adminService.AddQuesAnswer(quesAnsCreateDto);
            if (isDataPushed > 0)
            {
                TempData["DataSaved"] = "Saved Successfully";
            }

            return RedirectToAction("QuesAnsCreate");
        }

        public async Task<ActionResult> AddTechnology()
        {
            var userInfo = JsonConvert.DeserializeObject<Roles>(HttpContext.Session.GetString("SessionUser"));
            ViewBag.UserName = userInfo.UserName;
            if (TempData["TechDataSave"] != null)
            {
                ViewBag.TechDataSave = TempData["TechDataSave"].ToString();
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddTechnology(TechnologyDto technologyDto)
        {
            var userInfo = JsonConvert.DeserializeObject<Roles>(HttpContext.Session.GetString("SessionUser"));
            ViewBag.UserName = userInfo.UserName;
            if (!ModelState.IsValid) return View();
            await _adminService.AddTechnology(technologyDto);
            TempData["TechDataSave"] = "Data Saved Successfully";
            return RedirectToAction("AddTechnology");
        }

        public async Task<ActionResult> CandiateResult()
        {
            var userInfo = JsonConvert.DeserializeObject<Roles>(HttpContext.Session.GetString("SessionUser"));
            ViewBag.UserName = userInfo.UserName;
            var canResult = await _adminService.GetAllResult();
            return View(canResult);
        }

        public async Task<ActionResult> ViewQuestionAnswer()
        {
            DropdownUser();
            var viewQuestionAns =  _adminService.GetAllQuestionAnswer();
            return View(viewQuestionAns.Result);
        }

        private void DropdownUser()
        {
            var userInfo = JsonConvert.DeserializeObject<Roles>(HttpContext.Session.GetString("SessionUser"));
            ViewBag.UserName = userInfo.UserName;
            var enumData = from CandidateLevel e in Enum.GetValues(typeof(CandidateLevel))
                           select new
                           {
                               ID = (int)e,
                               Name = e.ToString()
                           };
            ViewBag.EnumList = new SelectList(enumData, "ID", "Name");
        }
    }
}

OnlineExamination/Controllers/JobseekerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.VisualBasic;
using Newtonsoft.Json;
using OnlineExamination.Controllers;
using OnlineExamination.Models;
using OnlineExamination.Models.DTO;
using OnlineExamination.Services;
using static OnlineExamination.Models.EnumData;

namespace OnlineExaminationWeb.Controllers
{
    [Authorize(Policy = "JobSeekerOnly")]
    public class JobseekerController : Controller
    {

        private readonly ILogger<AccountController> _logger;
        private readonly IJobSeekerService _jobSeekerService;
        private readonly IAdminService _adminService;
        private IConfiguration _configuration;

        public JobseekerController(ILogger<AccountController> logger, IJobSeekerService jobSeekerService, IConfiguration configuration, IAdminService adminService)
        {
            _logger = logger;
            _jobSeekerService = jobSeekerService;
            _configuration = configuration;
            _adminService = adminService;
            var enumData = from CandidateLevel e in Enum.GetValues(typeof(CandidateLevel))
                           select new
                           {
                               ID = (int)e,
                               Name = e.ToString()
                           };
            ViewBag.EnumList = new SelectList(enumData, "ID", "Name");
            
        }

        public async Task<ActionResult> Index()
        {
            DropdownUser();
            if (TempData["Notification"] != null) { 
            ViewBag.Notification = TempData["Notification"].ToString(); 
            }
            ViewBag.Tech = new SelectList(await _adminService.BindTechDropDownList(), "Id", "TechName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(StartTestDto startTestDto)
        {
            if (!ModelState.IsValid)
            {
                DropdownUser();
                ViewBag.Tech = new SelectList(await _adminService.BindTechDropDownList(), "Id", "TechName");
                return View();
            }
            DropdownUser();
            ViewBag.Tech = new SelectList(await _adminService.BindTechDropDownList(), "Id", "TechName");
            TempData["question"] = JsonConvert.SerializeObject(startTestDto);
            return RedirectToAction("OnlineTest");
        }


        public async Task<ActionResult> OnlineTest()
        {
            var userInfo = JsonConvert.DeserializeObject<Roles>(HttpContext.Session.GetString("SessionUser"));
            ViewBag.UserName = userInfo.UserName;
            var appData = _configuration.GetSection("ExaminationTimeSetting").Get<ExaminationTimeSetting>();
            ViewBag.minutes = appData.Time;
            var questions = JsonConvert.DeserializeObject<StartTestDto>(TempData["question"].ToString());
            TempData.Keep("question");
            var getQuestions = await _jobSeekerService.GetQuestionsByTechAndExperience(questions);
            if (getQuestions.Count == 0)
            {
                TempData["Notification"] = "Question is not found";
                return RedirectToAction("Index");
            }
            List<OnlineTestDto> obj = new List<OnlineTestDto>();
            obj.AddRange(getQuestions);
            TempData["QuesWOperation"] = JsonConvert.SerializeObject(getQuestions);
            TempData.Keep("QuesWOperation");
            ViewBag.TotalNoQuestion = getQuestions.Count();
            TempData["TotalNoQuestion"] = ViewBag.TotalNoQuestion;
            TempData.Keep("TotalNoQuestion");
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> OnlineTest(List<OnlineTestDto> onlineTestViewModel)
        {
            var QuesWOperation = JsonConvert.DeserializeObject<List<OnlineTestDto>>(TempData["QuesWOperation"].ToString());
            Int32 totalNoOFQuestion = Convert.ToInt32(TempData["TotalNoQuestion"].ToString());
            Int32 correctAns = 0; Int32 tQettempt = 0;
            if (onlineTestViewModel != null && onlineTestViewModel.Count() > 0)
            {
                foreach (var item in onlineTestViewModel)
                {
                    if (item.SelectedAnswer != null)
                    {
                        if (item.AnswerName.Trim().ToLower() == item.SelectedAnswer.Trim().ToLower())
                        {
                            correctAns++;
                            tQettempt++;

                        }
                        else
                        {
                            tQettempt++;
                        }
                    }                           
                    else {
                        tQettempt++;
                    }
                }
            }
            var userInfo = JsonConvert.DeserializeObject<Roles>(HttpContext.Session.GetString("SessionUser"));
            ViewBag.UserName = userInfo.UserName;
            var calPercentage = (correctAns * (100 / totalNoOFQuestion));
            Result results = new Result()
            {
                CorrectAnswers = correctAns,
                TotalQuestionEttempt = tQettempt,
                NoOfQuestions = totalNoOFQuestion.ToString(),
                ExamDate = DateAndTime.Now,
                CandidateName = userInfo.UserName,
                EmailId = userInfo.Email,
                Results = calPercentage >= 50 ? CandiateResult.Pass.ToString() : CandiateResult.Fail.ToString(),
                Percentage = Convert.ToString(calPercentage) + '%'
            };

            return RedirectToAction("Result", results);
        }

        public async Task<ActionResult> Result(Result result)
        {
            if (result != null)
            {
               await _jobSeekerService.AddCandidateResult(result);
            }
            DropdownUser();
          return View(result);
        }

        private void DropdownUser()
        {
            var userInfo = JsonConvert.DeserializeObject<Roles>(HttpContext.Session.GetString("SessionUser"));
            ViewBag.UserName = userInfo.UserName;
            var enumData = from CandidateLevel e in Enum.GetValues(typeof(CandidateLevel))
                           select new
                           {
                               ID = (int)e,
                               Name = e.ToString()
                           };
            ViewBag.EnumList = new SelectList(enumData, "ID", "Name");
         }
    }
}

OnlineExamination/Views/Shared/_AdminLayoutPage.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineExamination</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Admin" asp-action="Index">OnlineExamination</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="AddTechnology">AddTechnology</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="QuesAnsCreate">QuesAnsCreate</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="ViewQuestionAnswer">ViewQuesAns</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="CandiateResult">Result</a>
                        </li>
                    </ul>
                </div>
            <div style="float: right;">
            <span class="">Welcome @ViewBag.UserName</span>
            <span class=""><a asp-area="" asp-controller="Account" asp-action="LogOut">LogOut</a></span>
        </div>
            </div>
        </nav>
       
    </header>
  <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - OnlineExamination - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OnlineExamination/Views/Shared/_JobseekerLayoutPage.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineExamination</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body onload="startCountDown(@ViewBag.minutes);">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Jobseeker" asp-action="Index">OnlineExamination</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            
            <div style="float: right;">
            <span class="">Welcome @ViewBag.UserName</span>
            <span class=""><a asp-area="" asp-controller="Account" asp-action="LogOut">LogOut</a></span>
        </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - OnlineExamination - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OnlineExamination/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineExamination</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <div style="height:550px;" class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - OnlineExamination - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>